apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: 01-jump-app-nginx-vs-se
objects:
  - apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: nginx
    spec:
      exportTo:
        - "."
      hosts:
      - nginx.example.com
      ports:
      - number: 80
        name: http
        protocol: HTTP
      - number: 443
        name: https
        protocol: HTTPS
      resolution: DNS
      endpoints:
      - address: my-nginx.${USER_NAMESPACE}-mesh-external.svc.cluster.local
        ports:
          https: 443
  - apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: nginx
    spec:
      hosts:
      - nginx.example.com
      exportTo:
        - "."
      tls:
      - match:
        - port: 443
          sniHosts:
          - nginx.example.com
        route:
        - destination:
            host: nginx.example.com
            port:
              number: 443
          weight: 100
parameters:
- description: Tutorial User Namespace
  displayName: Tutorial User Namespace
  name: USER_NAMESPACE
  required: true
- description: Openshift Apps Domain
  displayName: Openshift Apps Domain
  name: OCP_APPS_DOMAIN
  required: true