apiVersion: v1
kind: Template
metadata:
  name: jump-app-gws-template
objects:
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: back-golang
    spec:
      selector:
        istio: ingressgateway
        servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: ${USER_NAMESPACE}-credential
          hosts:
          - back-golang-fail-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}
  - apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: back-golang
    spec:
      gateways:
      - back-golang
      - mesh
      hosts:
      - back-golang-${USER_NAMESPACE}.${OCP_APPS_DOMAIN}
      - back-golang.${USER_NAMESPACE}.svc.cluster.local
      - back-golang
      http:
      - route:
          - destination:
              host: back-golang-fail.${USER_NAMESPACE}.svc.cluster.local
              subset: v1
            weight: 100
  - apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: back-golang
    spec:
      host: back-golang.${USER_NAMESPACE}.svc.cluster.local
      subsets:
      - name: v1
        labels:
          version: fail
parameters:
  - description: Tutorial User Namespace
    displayName: Tutorial User Namespace
    name: USER_NAMESPACE
    required: true
  - description: Openshift Apps Domain
    displayName: Openshift Apps Domain
    name: OCP_APPS_DOMAIN
    required: true